name: nf_denovo_transcriptome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp=0.23.2
  - bbmap=38.96
  - pigz=2.8
  - spades=3.15.5
  - trinity=2.15.2
  - busco=5.4.7
  - python=3.9
  - nextflow=23.10.0
  - numpy
  - pandas 